experiment:
  name: AE_KL_hybrid_1024_16_full

model:
  model_version: "hybrid_1024_16"
  in_chans: 69
  out_chans: 69
  img_size: [128, 256]
  stem_dims: [256, 512, 1024]
  embed_dim: 1024
  latent_dim: 552
  depth: 16
  num_heads: 16
  mlp_ratio: 4.0
  qkv_bias: true
  window: true
  window_size: [[4, 4], [4, 8], [8, 4]]
  interval: 4
  drop_path_rate: 0.0
  sample_posterior: false
  learnable_pos: true

dataset:
  train:
    data_dir: huawei_100p:s3://ai4earth/era5_np128x256
    file_stride: 1
    train_stride: 1
  valid:
    data_dir: huawei_100p:s3://ai4earth/era5_np128x256
    file_stride: 1
    train_stride: 7

optimizer:
  lr: 1.0e-4
  weight_decay: 1.0e-2

scheduler:
  warmup_ratio: 0.05
  num_cycles: 0.5

loss:
  kl_weight: 2.0e-5
  enable_kl: true

trainer:
  epochs: 30
  batch_size: 8
  valid_batch_size: 8
  log_interval: 50
  grad_clip: 1.0
  refresh_dataloader_each_epoch: true
  valid_num_workers: 4
  save_optimizer_in_snapshot: false
  save_latest_snapshot: false
  save_best_checkpoint: true
  save_final_checkpoint: false
